name: Python Linting

on:
  push:
    paths:
    - '**.md'
  pull_request:
    paths:
    - '**.md'

jobs:
  flake8-lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
      
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 markdown

    - name: Extract Python code from Markdown
      run: |
        python -c "
        import markdown

        def extract_python_code(md_file):
            md = markdown.Markdown(extensions=['fenced_code'])

            with open(md_file) as file:
                html = md.convert(file.read())

            code_blocks = re.findall('<code>(.*?)</code>', html, re.DOTALL)
            python_code = [block for block in code_blocks if block.startswith('python')]

            return '\n'.join(python_code)

        md_files = glob.glob('**/*.md', recursive=True)
        python_code = '\n'.join(extract_python_code(md_file) for md_file in md_files)

        with open('extracted.py', 'w') as file:
            file.write(python_code)
        "

    - name: Run flake8 Linting
      run: |
        pip install flake8
        flake8 extracted.py
