site_name: 2024 - Spring - BIOL 4701 Biology Capstone Syllabus - Matthis
theme: 
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.sync
  language: en
  palette:
  - scheme: default
    toggle:
      icon: material/toggle-switch-off-outline
      name: switch to dark mode
    primary: teal
    accent: purple
  - scheme: slate
    toggle:
      icon: material/toggle-switch
      name: switch to light mode
    primary: teal
    accent: lime

plugins:
  - search
  - mermaid2

extra:
  social:
  - icon: fontawesome/brands/github
    link: https://github.com/NeuralControlHumanMovement-2023-Summer1/main_course_repo

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
